// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgczGdy1jO6PwI_oRaFF_sTH81vqK-z7A',
    appId: '1:19011815858:web:27aac8facaceb835e13cab',
    messagingSenderId: '19011815858',
    projectId: 'dsadsadsa-8f78a',
    authDomain: 'dsadsadsa-8f78a.firebaseapp.com',
    storageBucket: 'dsadsadsa-8f78a.firebasestorage.app',
    measurementId: 'G-KW1F1ED43B',
    // FIX: databaseURL required for Realtime Database on web.
    // Without this, FirebaseDatabase.instance throws "Cannot parse Firebase url".
    databaseURL: 'https://dsadsadsa-8f78a-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbzzvPXBiqmofojbutB-bMsk1qgt-eD08',
    appId: '1:19011815858:android:8e49d0ea87de0c3de13cab',
    messagingSenderId: '19011815858',
    projectId: 'dsadsadsa-8f78a',
    storageBucket: 'dsadsadsa-8f78a.firebasestorage.app',
    databaseURL: 'https://dsadsadsa-8f78a-default-rtdb.firebaseio.com',
  );

}